import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Body } from "@/components/Body";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { heIL } from "@clerk/localizations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      localization={heIL}
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" dir="rtl">
        <body className={inter.className}>
          <Body>
            <Header />
            {children}
            <Footer />
          </Body>
        </body>
      </html>
    </ClerkProvider>
  );
}
